### ISSUE TITLE
[Bug] Modules not found when starting the app

### ISSUE THREAD

**Issue by TheUndex** [creativetimofficial/ct-vision-ui-dashboard-pro-react#1]
### Version
1.0.0
### Reproduction link
https://github.com/creativetimofficial/ct-vision-ui-dashboard-pro-react
### Operating System
Windows 11 & Ubuntu 20.04.3 LTS
### Device
PC & Server
### Browser & Version
Firefox 96
### Steps to reproduce
1. Install NodeJS LTS
2. Unzip the zipped file
3. Do npm install [ERROR 1]
4. Because npm install won't work, I do npm install --legacy-peer-deps which works for me
5. Do npm start and wait for the ERROR 2 to happen
### What is expected?
Well, showing me the dashboard i guess
### What is actually happening?
ERROR 1 - npm install
Screenshot  https://up.picr.de/42839685au.png

ERROR 2 - npm start
Screenshot  https://up.picr.de/42839686kj.png

---
### Additional comments
The notice on the documentation does not help in any way since the jsconfig.json is included in the project.
"If you have an error something containing Module not found you need to add our jsconfig.json file to your project"

**Comment by simmmpleweb** [comment]
Hi, @TheUndex ! Thanks for using our products. The problem is that the dashboard was developed on the latest version of React(17.0.2), and one of the other dependencies (delowar/react-circle-progressbar) asks for an older version of React. Try using `npm install --force`, that should force the peer dependencies to be ignored.
Regards, Vlad.
